version: '3.8'
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis-data:/data

# optionally add node server, retrieval, llm containers too

volumes:
  redis-data:
  pgdata:
